# -*- coding: utf-8 -*-
"""AP1_ConvCasamento.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z-u6tYmLz3OCb5eC4Ou5WmULonPvU64V
"""

lista_noivo = set()
lista_noiva = set()
lista_ambos = set()

def lista_convidados():

    print("")
    print("Caso queira encerrar o processo, escreva (ACABOU)")
    print("")
    convidado = input("Escreva o nome do convidado: ").strip().lower()

    if convidado == "acabou":
      lista_total = lista_noivo.union(lista_noiva).union(lista_ambos)
      print("")
      print(f"Convidados Noivo: {', '.join([nome.title() for nome in lista_noivo - lista_noiva])}")
      print(f"Convidados Noiva: {', '.join([nome.title() for nome in lista_noiva - lista_noivo])}")
      print(f"Convidados de ambos: {', '.join([nome.title() for nome in lista_ambos])}")
      print(f"Quantidade de convidados: {len(lista_total)}")
      print("")
      lista_total.clear()
      lista_noivo.clear()
      lista_noiva.clear()
      lista_ambos.clear()
      return

    escolha = int(input(f"{convidado.title()} é convidado do Noivo(1) ou da Noiva(2)? "))

    if escolha == 1:
      if convidado in lista_noivo:
        print("")
        print(f"Desculpe, {convidado.title()} já consta nessa lista, tente novamente")
      elif convidado in lista_ambos:
        print("")
        print(f"Desculpe, {convidado.title()} já consta na lista da noiva, movendo para lista de ambos, tente outro nome")
      elif convidado in lista_noiva:
        lista_noiva.remove(convidado)
        lista_ambos.add(convidado)
        print("")
        print(f"{convidado.title()} já estava na lista da Noiva, foi movido para a lista de ambos")
      else:
        lista_noivo.add(convidado)
        print("")
        print(f"{convidado.title()} foi adicionado à lista do noivo")

    if escolha == 2:
      if convidado in lista_noiva:
        print("")
        print(f"Desculpe, {convidado.title()} já consta nessa lista, tente novamente")
      elif convidado in lista_ambos:
        print("")
        print(f"Desculpe, {convidado.title()} já consta na lista do noivo, movendo para lista de ambos, tente novamente")
      elif convidado in lista_noivo:
        lista_noivo.remove(convidado)
        lista_ambos.add(convidado)
        print("")
        print(f"{convidado.title()} já estava na lista do Noivo, foi movido para a lista de ambos")
      else:
        lista_noiva.add(convidado)
        print("")
        print(f"{convidado.title()} foi adicionado à lista do noiva")

    lista_convidados()