# -*- coding: utf-8 -*-
"""AP1_ListaCasamento

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JoxOM52bhyYlgwMS-wQC1ra6_lfPngZ0
"""

lista_noivo = set()
lista_noiva = set()
lista_ambos = set()

def lista_convidados(convidados):

    if not convidados:
        return

    convidado = convidados[0]

    if convidado == "ACABOU":
        lista_total = lista_noivo.union(lista_noiva).union(lista_ambos)
        print("")
        print(f"Convidados Noivo: {', '.join(lista_noivo - lista_noiva)}")
        print(f"Convidados Noiva: {', '.join(lista_noiva - lista_noivo)}")
        print(f"Convidados de ambos: {', '.join(lista_ambos)}")
        print(f"Quantidade de convidados: {len(lista_total)}")
        lista_noiva.clear()
        lista_noivo.clear()
        lista_ambos.clear()
        lista_total.clear()
        return

    escolha = int(input("O convidado é do Noivo(1) ou da Noiva(2)? "))

    if escolha == 1:
      if convidado in lista_noivo:
        print("Desculpe, o nome já consta nessa lista, tente novamente")
      elif convidado in lista_ambos:
        print("Desculpe, o nome já consta na lista da noiva, adicionando na lista de ambos, tente novamente")
      elif convidado in lista_noiva:
        lista_noiva.remove(convidado)
        lista_ambos.add(convidado)
      else:
        lista_noivo.add(convidado)

    if escolha == 2:
      if convidado in lista_noiva:
        print("Desculpe, o nome já consta nessa lista, tente novamente")
      elif convidado in lista_ambos:
        print("Desculpe, o nome já consta na lista do noivo, adicionando na lista de ambos, tente novamente")
      elif convidado in lista_noivo:
        lista_noivo.remove(convidado)
        lista_ambos.add(convidado)
      else:
        lista_noiva.add(convidado)

    lista_convidados(convidados[1:])